language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
install:
  - sudo apt-get update -qq
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION coveralls matplotlib
  - source activate test-environment
  - conda config --add channels bioconda
  - conda install --quiet advntr

script: coverage run --source=advntr setup.py test

after_success:
  - coveralls

branches:
  only:
  - master
